<!-- GENERATED BY ONLINE TOOL: PDF to HTML -->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<HTML>
<HEAD>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<META http-equiv="X-UA-Compatible" content="IE=8">
<TITLE>bcl_29218173.htm</TITLE>
<META name="generator" content="BCL easyConverter SDK 5.0.140">
<STYLE type="text/css">

body {
    margin-top: 0px;
    margin-left: 0px;
    /* agar background-color tetap tampil ketika saat print preview */
    color-adjust: exact;
    -webkit-print-color-adjust: exact;
}

#page_1 {position:relative; overflow: hidden;margin: 50px 0px 195px 0px;padding: 0px;border: none;width: 816px;}

#page_1 #p1dimg1 {position:absolute;top:0px;left:509px;z-index:-1;width:210px;height:779px;}
#page_1 #p1dimg1 #p1img1 {width:210px;height:779px;}




.ft0{font: 15px 'Times New Roman';color: #595959;line-height: 17px;}
.ft1{font: bold 15px 'Times New Roman';color: #595959;line-height: 17px;}
.ft2{font: bold 19px 'Times New Roman';text-decoration: underline;line-height: 22px;}
.ft3{font: 16px 'Times New Roman';line-height: 19px;}
.ft4{font: bold 16px 'Times New Roman';line-height: 19px;}
.ft5{font: 12px 'Times New Roman';line-height: 15px;}
.ft6{font: 1px 'Times New Roman';line-height: 1px;}
.ft7{font: 16px 'Times New Roman';line-height: 17px;}
.ft8{font: 1px 'Times New Roman';line-height: 17px;}
.ft9{font: 1px 'Times New Roman';line-height: 18px;}
.ft10{font: bold 16px 'Times New Roman';line-height: 18px;}
.ft11{font: 16px 'Times New Roman';line-height: 18px;}
.ft12{font: 16px 'Times New Roman';line-height: 26px;}

.p0{text-align: left;padding-left: 103px;margin-top: 0px;margin-bottom: 0px;}
.p1{text-align: left;padding-left: 103px;margin-top: 3px;margin-bottom: 0px;}
.p2{text-align: left;padding-left: 103px;margin-top: 2px;margin-bottom: 0px;}
.p3{text-align: left;padding-left: 367px;margin-top: 20px;margin-bottom: 0px;}
.p4{text-align: left;padding-left: 96px;margin-top: 42px;margin-bottom: 0px;}
.p5{text-align: left;padding-left: 96px;margin-top: 12px;margin-bottom: 0px;}
.p6{text-align: left;padding-left: 96px;margin-top: 11px;margin-bottom: 0px;}
.p7{text-align: left;margin-top: 0px;margin-bottom: 0px;white-space: nowrap;}
.p8{text-align: left;padding-left: 7px;margin-top: 0px;margin-bottom: 0px;white-space: nowrap;}
.p9{text-align: left;padding-left: 71px;margin-top: 0px;margin-bottom: 0px;white-space: nowrap;}
.p10{text-align: left;padding-left: 18px;margin-top: 0px;margin-bottom: 0px;white-space: nowrap;}
.p11{text-align: left;padding-left: 32px;margin-top: 0px;margin-bottom: 0px;white-space: nowrap;}
.p12{text-align: left;padding-left: 6px;margin-top: 0px;margin-bottom: 0px;white-space: nowrap;}
.p13{text-align: right;padding-right: 37px;margin-top: 0px;margin-bottom: 0px;white-space: nowrap;}
.p14{text-align: right;padding-right: 7px;margin-top: 0px;margin-bottom: 0px;white-space: nowrap;}
.p15{text-align: left;padding-left: 96px;/*padding-right: 174px*/;padding-right: 100px;margin-top: 30px;margin-bottom: 0px;}
.p16{text-align: left;padding-left: 528px;margin-top: 9px;margin-bottom: 0px;}
.p17{text-align: right;padding-right: 110px;margin-top: 96px;margin-bottom: 0px;}

.td0{padding: 0px;margin: 0px;width: 144px;vertical-align: bottom;}
.td1{padding: 0px;margin: 0px;width: 450px;vertical-align: bottom;}
.td2{width: 0!important; border-left: #000000 1px solid;border-right: #000000 1px solid;border-top: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 37px;vertical-align: bottom;}
.td3{border-right: #000000 1px solid;border-top: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 208px;vertical-align: bottom;}
.td4{border-top: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 119px;vertical-align: bottom;}
.td5{border-right: #000000 1px solid;border-top: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 13px;vertical-align: bottom;}
.td6{border-right: #000000 1px solid;border-top: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 81px;vertical-align: bottom;}
.td7{border-right: #000000 1px solid;border-top: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 133px;vertical-align: bottom;}
.td8{width: 0!important;border-left: #000000 1px solid;border-right: #000000 1px solid;padding: 0px;margin: 0px;width: 37px;vertical-align: bottom;}
.td9{border-right: #000000 1px solid;padding: 0px;margin: 0px;width: 208px;vertical-align: bottom;}
.td10{padding: 0px;margin: 0px;width: 119px;vertical-align: bottom;}
.td11{border-right: #000000 1px solid;padding: 0px;margin: 0px;width: 13px;vertical-align: bottom;}
.td12{border-right: #000000 1px solid;padding: 0px;margin: 0px;width: 81px;vertical-align: bottom;}
.td13{border-right: #000000 1px solid;padding: 0px;margin: 0px;width: 133px;vertical-align: bottom;}
.td14{border-left: #000000 1px solid;border-right: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 37px;vertical-align: bottom;}
.td15{border-right: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 208px;vertical-align: bottom;}
.td16{border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 119px;vertical-align: bottom;}
.td17{border-right: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 13px;vertical-align: bottom;}
.td18{border-right: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 81px;vertical-align: bottom;}
.td19{border-right: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 133px;vertical-align: bottom;}
.td20{width: 0!important;border-left: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 38px;vertical-align: bottom;}
.td21{border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 209px;vertical-align: bottom;}
.td22{border-right: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 214px;vertical-align: bottom;}
.td23{border-right: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 423px;vertical-align: bottom;}
.td24{border-right: #000000 1px solid;border-bottom: #000000 1px solid;padding: 0px;margin: 0px;width: 95px;vertical-align: bottom;}

.tr0{height: 19px;}
.tr1{height: 20px;}
.tr2{height: 17px;}
.tr3{height: 18px;}

.t0{width: 594px;margin-left: 96px;margin-top: 41px;font: 16px 'Times New Roman';}
.t1{width: 596px;margin-left: 110px;margin-top: 40px;font: bold 16px 'Times New Roman';}

#invoice-table {
    border-collapse: collapse;
    /* width: 596px; */
    width: 635px;
    margin-left: 110px;
    margin-top: 40px;
    font-family: 'Times New Roman';
    font-size: 16px;
}
#invoice-table td, #invoice-table th {
    border: 1px solid black;
    padding: 2px 5px;
    box-sizing: border-box;
}
#invoice-table th, #invoice-table .col-header {
    background-color: #ddd;
    font-weight: bold;
    text-align: center;
}
.text-right {text-align: right;}
.text-center {text-align: center;}

#logo-header {float: right; margin-right: 104px;}
#footer-letter {float: right; margin-right: 104px; margin-top: 9px; text-align: center; font-size: 16px;}
</STYLE>
</HEAD>

<BODY>
<DIV id="page_1">

<img id="logo-header" src="{{ asset('assets/images/dsantren-logo-for-invoice.png') }}" />

<P class="p0 ft0">PT. Dsantren Kreatif Global</P>
<P class="p1 ft0">Jalan PH H. Mustofa, Ruko Grand Surapati Core</P>
<P class="p0 ft0">Blok M 30, Kota Bandung, Jawa Barat</P>
<P class="p2 ft1"><NOBR>0811-2223-806</NOBR></P>
<P class="p1 ft1">NPWP <NOBR>80.960.434.1-428.000</NOBR></P>
<P class="p3 ft2">INVOICE</P>
<P class="p4 ft3">Kepada:</P>
<P class="p5 ft4">{{ $input['department'] }}</P>
<P class="p5 ft4">{{ $input['company_name'] }}</P>
<P class="p6 ft4">di</P>
<P class="p5 ft4">{{ $input['company_address'] }}</P>
<TABLE cellpadding=0 cellspacing=0 class="t0">
<TR>
    <TD class="tr0 td0"><P class="p7 ft3">No. Invoice</P></TD>
    <TD class="tr0 td1"><P class="p7 ft5"><SPAN class="ft3">: {{ str_pad($invoice_number, 3, '0', STR_PAD_LEFT) }}/INV/{{ $input['letter_receiver'] }}/{{ numberToRomanRepresentation(date('n')) }}/{{ date('Y') }} </SPAN></P></TD>
</TR>
<TR>
    <TD class="tr0 td0"><P class="p7 ft3">Pembayaran ke-</P></TD>
    <TD class="tr0 td1">
        <P class="p7 ft5">
            <SPAN class="ft3">:
                {{ str_replace_last_occurrence(',', ' dan', implode(', ', array_pluck($termin_details->toArray(), 'serial_number'))) }}
            </SPAN>
        </P>
    </TD>
</TR>
</TABLE>

<!-- KOMPONEN UTAMA -->
<TABLE id="invoice-table">
<thead>
    <tr>
        <th colspan="2">Deskripsi</th>
        <th>Harga Satuan</th>
        <th>Kuantitas</th>
    </tr>
</thead>
<tbody>
    <tr>
        <td colspan="2">{{ $project->name }}</td>
        <!-- TODO: pindahkan number_format ke bentuk Helper -->
        <td>Rp.@money($project->price),-</td>
        <td class="text-center">{{ $project->quantity }}</td>
    </tr>
    <tr>
        <td class="col-header" colspan="4">&nbsp;</td>
    </tr>
    <tr>
        <td class="text-right" colspan="3">Jumlah Tagihan</td>
        <td>Rp.@money($project->price * $project->quantity),-</td>
    </tr>
    <tr>
        <td class="text-right" colspan="3">Jumlah Sisa Tagihan</td>
        <td><b>Rp.@money(($project->price * $project->quantity) - $total_paid_amount),-</b></td>
    </tr>
    {{-- only show Riwayat Pembayaran Terakhir when data available --}}
    @if (count($project->termin->payments) > 0)
    <tr>
        <td class="col-header" colspan="4">Riwayat Pembayaran Terakhir</td>
    </tr>
    <tr>
        <th class="col-header">Pembayaran Ke-</th>
        <th class="col-header">Jumlah Tagihan</th>
        <th class="col-header">Jumlah Yang Dibayar</th>
        <th class="col-header">Keterangan</th>
    </tr>
    <!--
    <tr>
        <td class="text-right">Pembayaran ke-1 (Cash, 7 Agu 2018)</td>
        <td>Rp.40.000.000,-</td>
        <td>LUNAS</td>
    </tr>
    <tr>
        <td class="text-right">Pembayaran ke-2 (Cash, 7 Agu 2018)</td>
        <td>Rp.40.000.000,-</td>
        <td>SISA Rp.10.000.000,-</td>
    </tr>
    <tr>
        <td class="text-right">Pembayaran ke-2 (Cash, 7 Agu 2018)</td>
        <td>Rp.10.000.000,-</td>
        <td>LUNAS</td>
    </tr>
    <tr>
        <td class="text-right">Pembayaran ke-4 (Cash, 7 Agu 2018)</td>
        <td>Rp.40.000.000,-</td>
        <td>Rp.40.000.000,-</td>
    </tr>
    -->
    {{-- Termin Payment already ordered by pay_date --}}
    @foreach ($project->termin->payments as $termin_payment)
    <tr>
        <td>ke-{{ $termin_payment->termin_detail->serial_number }} (Cash, {{ date('d-M-Y', strtotime($termin_payment->pay_date)) }})</td>
        <td>Rp.@money($termin_payment->termin_detail->amount),-</td>
        <td>Rp.@money($termin_payment->amount),-</td>
        <td>
            @if ($termin_payment->amount == $termin_payment->termin_detail->amount)
            LUNAS
            @elseif (($remaining = getRemainingAmountTerminPayment($termin_payment, $project->termin->payments)) == 0)
            LUNAS
            @else ($remaining > 0)
            SISA Rp.@money($remaining),-
            @endif
        </td>
    </tr>
    @endforeach
    @endif
    <tr>
        <td class="col-header"" colspan="4">Tagihan Saat Ini</td>
    </tr>
    @foreach ($termin_details as $termin_detail)
    <tr>
        @if ($termin_detail->paid_amount == 0)
        <td class="text-right" colspan="3">Tagihan di Pembayaran ke-{{ $termin_detail->serial_number }}</td>
        <td>Rp.@money($termin_detail->amount),-</td>
        @else
        <td class="text-right" colspan="3">Tagihan di Pembayaran ke-{{ $termin_detail->serial_number }} (BELUM LUNAS)</td>
        <td>Rp.@money($termin_detail->amount - $termin_detail->paid_amount),-</td>
        @endif
    </tr>
    @endforeach
</tbody>
</TABLE>

<P class="p15 ft12">Transfer pembayaran ke rekening {{ $bank->name }} {{ $bank->account_number }} a.n. {{ $bank->owner }} <br>Terima kasih atas kepercayaannya</P>

<div id="footer-letter">
    <p id="footer-letter--place-date">Bandung, {{ now()->format('d M Y') }}</p>
    <img id="footer-letter--logo" src="{{ asset('assets/images/dsantren-logo-for-invoice.png') }}" />
    <p id="footer-letter--name">Ruston Pirmansyah, S. Kom.</p>
</div>

</DIV>
</BODY>
</HTML>
